<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon />
    <AssemblyName>PacsCdTransfer</AssemblyName>
    <RootNamespace>PacsCdTransfer.App</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PacsCdTransfer.Core\PacsCdTransfer.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2957.106" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Web\app.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
